config/routes.rb
Rails.application.routes.draw do
  #user用
  devise_for :users,skip: [:passwords,], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
 

  root to: 'user/homes#top'
  get 'homes/about' => 'user/homes#about'
  get 'user/mypage' => 'user#mypage'
  get '/search', to: 'searchs#search'


  # 会員側のルーティング設定

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :followings, :followers
    end

  resources :relationships, only: [:create, :destroy]
  end

  get '/posts/change_auth', to: 'posts#change_auth'
  

  resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    get 'authorization', as: 'authorization'
  end

  resources :contacts, only: [:new, :create]
    post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
    post 'contacts/back', to: 'contacts#back', as: 'back'
    get 'done', to: 'contacts#done', as: 'done'


  end

app/models/user.rb
class User < ApplicationRecord
  attachment :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
   
  
  # 検索方法分岐
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  validates :name, length: {maximum: 20, minimum: 2}
  validates :age,  presence: true
  validates :sauna_years,  presence: true
  validates :number_of_sets,  presence: true
  validates :email, {presence: true, uniqueness: true}

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

   #GET /resource/sign_up
   def new
     super
   end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def my_page

  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])

    unless current_user.id == @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:success] = "You have updated user successfully."
    else
      @posts = Post.all
      render :edit
    end
  end

  def index
    @users = User.all
    @post = Post.new
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(PER)
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(PER)
  end


  private

  def user_params
    params.require(:user).permit(:name, :age, :sauna_yesrs, :number_of_sets, :image_id, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:mypage, :index, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @user = User.page(params[:page])
    @users = User.all
    @post = Post.new
  end


  def mypage
    redirect_to user_path(current_user)
  end

  def show
    @posts = @user.posts
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:success] = "You have updated user successfully."
    else
      @posts = Post.all
      render :edit
    end
  end



  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(PER)
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(PER)
  end


  private


  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age, :sauna_years, :number_of_sets, :image, :admin)
  end
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/relationships_helper.rb
module User::RelationshipsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>氏名</th>
      <th class=text-right>年齢</th>
      <th class="text-right">サウナ歴</th>
      <th class="text-right">セット回数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <th><%= attachment_image_tag(user, :image, :fill, 80, 80, fallback: "no_image.jpg") %></th>
        <th><%= user.name %></th>
        <th class="text-right"><%= user.age %>歳</td>
        <th class="text-right"><%= user.sauna_years %></td>
        <th class="text-right"><%= user.number_of_sets %></td>
        <th><%= link_to '詳細', user_path(user), class: "user_#{user.id}" %></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<!DOCTYPE html>
	<html lang="en">
	<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<title>Full Width Pics - Start Bootstrap Template</title>
	<!-- Favicon-->
	<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
	<!-- Core theme CSS (includes Bootstrap)-->
	<link href="css/styles.css" rel="stylesheet" />
	</head>
	<body>
	<!-- Responsive navbar-->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#!">Start Bootstrap</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
	<% if user_signed_in? %>
	                <li class="nav-item border rounded-lg" style="margin-right: 20px;"><%= link_to "About", homes_about_path, class: 'nav-link text-dark' %></li>
	                <li class="nav-item border rounded-lg" style="margin-right: 20px;"><%= link_to "Mypage", user_path(current_user), class: 'nav-link text-dark' %></li>
	                <li class="nav-item border rounded-lg" style="margin-right: 20px;"><%= link_to "User", users_path, class: 'nav-link text-dark' %></li>
	                <li class="nav-item border rounded-lg" style="margin-right: 20px;"><%= link_to "Post", posts_path, class: 'nav-link text-dark' %></li>
	                <% if current_user.admin %>
	                <li class="nav-item border rounded-lg" style="margin-right: 20px;"><%= link_to "管理者", posts_path, class: 'nav-link text-dark' %></li>
	                <% end %>
	                <li class="nav-item border rounded-lg"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %></li>
	              <% else %>
	                <li class="nav-item border rounded-lg" style="margin-right: 20px;"><%= link_to "About", homes_about_path, class: 'nav-link text-dark' %></li>
	　　　　　　　　<li class="nav-item border rounded-lg" style="margin-right: 20px;"><%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %></li>
	                <li class="nav-item border rounded-lg"><%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %></li>
	              <% end %>
	</ul>
	</div>
	</div>
	</nav>
	<!-- Header - set the background image for the header in the line below-->
	<header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
	<div class="text-center my-5">
	<img class="img-fluid rounded-circle mb-4" src="https://dummyimage.com/150x150/6c757d/dee2e6.jpg" alt="..." />
	<h1 class="text-white fs-3 fw-bolder">Full Width Pics</h1>
	<p class="text-white-50 mb-0">Landing Page Template</p>
	</div>
	</header>
	<main class ="main">
      <%= yield %>
    </main>
	<!-- Content section-->
	<section class="py-5">
	<div class="container my-5">
	<div class="row justify-content-center">
	<div class="col-lg-6">
	<h2>Full Width Backgrounds</h2>
	<p class="lead">A single, lightweight helper class allows you to add engaging, full width background images to sections of your page.</p>
	<p class="mb-0">The universe is almost 14 billion years old, and, wow! Life had no problem starting here on Earth! I think it would be inexcusably egocentric of us to suggest that we're alone in the universe.</p>
	</div>
	</div>
	</div>
	</section>
	<!-- Image element - set the background image for the header in the line below-->
	<div class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/4ulffa6qoKA/1200x800')">
	<!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
	<div style="height: 20rem"></div>
	</div>
	<!-- Content section-->
	<section class="py-5">
	<div class="container my-5">
	<div class="row justify-content-center">
	<div class="col-lg-6">
	<h2>Engaging Background Images</h2>
	<p class="lead">The background images used in this template are sourced from Unsplash and are open source and free to use.</p>
	<p class="mb-0">I can't tell you how many people say they were turned off from science because of a science teacher that completely sucked out all the inspiration and enthusiasm they had for the course.</p>
	</div>
	</div>
	</div>
	</section>
	<!-- Footer-->
	<footer class="py-5 bg-dark">
	<div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
	</footer>
	<!-- Bootstrap core JS-->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
	<!-- Core theme JS-->
	<script src="js/scripts.js"></script>
	</body>
	</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class='container'>
  <div class='row'>
    <div class='col-md-12 offset-md-1'>
  		<h2>User Page</h2>
  	</div>
  		    <%= form_with model: @user, local: true do |f| %>


          <div class="field">
            <%= f.label "氏名" %><br />
            <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
          </div>

          <div class="field">
            <%= f.label "メールアドレス" %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label "年齢"%><br />
            <%= f.text_field :age, autofocus: true, autocomplete: "age" %>
          </div>

          <div class="form-group">
            <%= f.label :sauna_years,"サウナ歴" %><br />
            <%= f.select :sauna_years,[["1年目", "1年目"], ["2年目", "2年目"], ["3年目", "3年目"],["4年目", "4年目"],["5年目", "5年目"],["6年目", "6年目"],["7年目", "7年目"],["8年目", "8年目"],["9年目", "9年目"],["10年以上", "10年目"]], include_blank: "選択して下さい",class:"form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :number_of_sets,"セット回数（交代浴）" %><br />
            <%= f.select :number_of_sets,[["1回", "1回"], ["2回", "2回"], ["3回", "3回"],["4回以上", "4回以上"]], include_blank: "選択して下さい",class:"form-control" %>
          </div>

          <div class="form-group">
            <%= "プロフィール画像" %><br />
            <%= f.attachment_field :image%>
          </div><br />

          <div class="actions">
            <%= f.submit "更新" %>
          </div><br />

          <div>
            <% if current_user.id == @user.id %>
            <%= link_to '削除', user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_#{@user.id}"%>
            <% end %>
          </div>

          <% end %>






  </div>

app/views/users/index.html.erb
<div class="row justify-content-end">
<% if user_signed_in? %>
  <%= render 'searchs/search' %>
<% end %>
</div>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>

       <h2>Users</h2>
       <%= render 'index',users: @users %>
    </div>
   </div>
</div>
<%= render 'layouts/fixed_btn' %>
<div class="row justify-content-center">
<%= paginate @user %>
</div>

app/views/users/mypage.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12 offset-md-1'>
  		<h2>USER SHOW</h2>

  <table class='table'>
  		  <tr>
  		    <td><%= link_to "ユーザー", users_path %>
            <td><%= attachment_image_tag(@user, :image, :fill, 100, 100, fallback: "no_image.jpg") %><br></td>
            <td><%= @user.name %></td>
            <td><%= @user.age %></td>
            <td><%= @user.sauna_years %></td>
            <td><%= @user.number_of_sets%></td>
          </td>
          <% if current_user.id == @user.id %>
          <td><%= link_to 'Edit', edit_user_path(@user), class: "btn btn-sm btn-success edit_user_#{@user.id}" %></td>
          <td><%= link_to 'Destroy', user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_#{@user.id}"%></td>
          <% end %>
      </table>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>
  		<h2>User Page</h2>

  <table class='table'>
  <thead>
    <tr>
      <th>ユーザ画像</th>
      <th>氏名</th>
      <th class=text-right>年齢</th>
      <th class="text-right">サウナ歴</th>
      <th class="text-right">セット回数</th>
      <th></th>
    </tr>
  		<tbody>
  		  <tr>
            <th><%= attachment_image_tag(@user, :image, :fill, 100, 100, fallback: "no_image.jpg") %></th>
            <th><%= @user.name %></th>
            <th class="text-right"><%= @user.age %></th>
            <th class="text-right"><%= @user.sauna_years %></th>
            <th class="text-right"><%= @user.number_of_sets%></th>
            <th>
            <% if current_user.id == @user.id %>
            <%= link_to '編集', edit_user_path(@user), class: "btn btn-sm btn-success edit_user_#{@user.id}" %>
            <%= link_to '削除', user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_#{@user.id}"%>
            <% end %>
            <%= link_to '戻る', users_path, class: "btn btn-sm btn-info" %>
            </th>
        </tr>
      </body>
  </table>

      <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>名前</th>
          <th>URL</th>
          <th>評価</th>
          <th>公認</th>
          <th>コメント</th>
          <th>いいね</th>
          <th>詳細</th>
        </tr>
      </thead>
      <tbody>
        <%= render 'posts/index', posts: @posts  %>
      </tbody>
    </table>
    
    <%= render 'layouts/fixed_btn' %>