config/routes.rb
Rails.application.routes.draw do
  #user用
  devise_for :users,skip: [:passwords,], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
 

  root to: 'user/homes#top'
  get 'homes/about' => 'user/homes#about'
  get 'user/mypage' => 'user#mypage'
  get '/search', to: 'searchs#search'


  # 会員側のルーティング設定

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :followings, :followers
    end

  resources :relationships, only: [:create, :destroy]
  end

  get '/posts/change_auth', to: 'posts#change_auth'
  

  resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    get 'authorization', as: 'authorization'
  end

  resources :contacts, only: [:new, :create]
    post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
    post 'contacts/back', to: 'contacts#back', as: 'back'
    get 'done', to: 'contacts#done', as: 'done'


  end

app/models/post.rb
class Post < ApplicationRecord
  attachment :sauna_image

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def liked(user)
    likes.find_by(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(sauna_name: content)
    elsif method == 'forward'
      Post.where('sauna_name LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('sauna_name LIKE ?', '%'+content)
    else
      Post.where('sauna_name LIKE ?', '%'+content+'%')
    end
  end

  validates :sauna_name, presence: true
  validates :address, presence: true
  validates :url, presence: true
  validates :sauna_image, presence: true
  validates :sauna_temperature, presence: true
  validates :water_bath_temperature, presence: true
  validates :outside_air_bath, presence: true
  validates :congestion, presence: true
  validates :time_zorn, presence: true
  validates :vending_machine, presence: true
  validates :evaluation, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @user = User.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
    redirect_to post_path(@post.id)
    flash[:success] = "You have created book successfully."
    else
      @posts = Post.all
    render 'new'
    end
  end

  def index
    @posts = Post.page(params[:page])
    @post = Post.new

  end

  def show
    @post = Post.find(params[:id])
    gon.post = @post
    @comment = Comment.new
    @comments = current_user.comments.new
    @posts = Post.all
    @user = @post.user
    @new_post = Post.new
  end



  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      redirect_to post_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post.id)
    flash[:success] = "You have updated book successfully."
    else
    render 'edit'
    end
  end

  def change_auth
    redirect_to posts_path and return unless current_user.admin

    post = Post.find(params[:id])
    if post.authorization
      post.update(authorization: false)
    else
      post.update(authorization: true)
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:sauna_name, :address, :url, :sauna_image, :sauna_temperature, :water_bath_temperature, :outside_air_bath, :congestion, :time_zorn, :vending_machine, :evaluation, :comment, :likes, :latitude, :longitude)
  end


end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <%= post.errors.count %>件のエラーが発生しました
  <% post.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class='container px-5 px-sm-3'>
  <div class='row'>
    <div class='col-md-12'>

<%= form_with model: post, local: true do |f| %>

  <div class="field">
    <%= f.label "施設名" %><br />
    <%= f.text_field :sauna_name, :placeholder => "東京THEサウナ", autocomplete: "sauna_name" %>
  </div></br>

  <div class="field">
    <%= f.label "住所" %><br />
    <%= f.text_field :address, :placeholder => "東京都渋谷区代々木神園町0-0", autocomplete: "address", size: 35 %>
  </div></br>

  <div class="field">
    <%= f.label "ホームページURL"%><br />
    <%= f.text_field :url, :placeholder => "https/sample/.com", autocomplete: "url" %>
  </div></br>

  <div class="form-group">
    <%= "サウナ画像" %><br />
    <%= f.attachment_field :sauna_image%></div></br>

  <div class="form-group">
    <%= f.label :sauna_temperature,"サウナ温度" %><br />
    <%= f.select :sauna_temperature,[["80℃", "80℃"], ["85℃", "85℃"], ["90℃", "90℃"],["95℃", "95℃"],["それ以上", "それ以上"]], include_blank: "選択して下さい",class:"form-control" %>
  </div></br>

  <div class="form-group">
    <%= f.label :water_bath_temperature,"水風呂温度" %><br />
    <%= f.select :water_bath_temperature,[["20℃", "20℃"], ["15℃", "15℃"], ["13℃", "13℃"],["10℃", "10℃"],["その他", "その他"]], include_blank: "選択して下さい",class:"form-control" %>
  </div></br>

  <div class="form-group">
    <%= f.label :outside_air_bath,"外気浴" %><br />
    <%= f.select :outside_air_bath,[["普通", "普通"], ["良い", "良い"], ["良くない", "良くない"]], include_blank: "選択して下さい",class:"form-control" %>
  </div></br>

  <div class="form-group">
    <%= f.label :congestion,"混雑具合" %><br />
    <%= f.select :congestion,[["普通", "普通"], ["混雑", "混雑"], ["空いてる", "空いてる"]], include_blank: "選択して下さい",class:"form-control" %>
  </div></br>

  <div class="form-group">
    <%= f.label :time_zorn,"時間帯" %><br />
    <%= f.select :time_zorn,[["9時〜12時", "9時〜12時"], ["12時〜15時", "12時〜15時"], ["15時〜18時", "15時〜18時"], ["18時〜21時", "18時〜21時"], ["21時〜24時", "21時〜24時"], ["その他", "その他"]], include_blank: "選択して下さい",class:"form-control" %>
  </div></br>

  <div class="form-group">
    <%= f.label :vending_machine,"瓶ジュース" %><br />
    <%= f.select :vending_machine,[["ある", "ある"], ["ない", "ない"]], include_blank: "選択して下さい",class:"form-control" %>
  </div></br>

  <div id="evaluate_stars">
    <label>評価</label>
  </div>

  <div class="actions">
    <%= f.submit "投稿" %>
  </div>
<% end %>

   </div>
  </div>
</div>

<script>
  $('#evaluate_stars').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'post[evaluation]',
    score:"<%= post.evaluation %>"
  });
</script>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
<div>
  <%= link_to post_path(post.id) do %>
  <tr>
      <th><%= attachment_image_tag post, :sauna_image, format: 'jpeg', size: "270x270" %></th>
      <th><%= post.sauna_name %></th>
      <% end %>
      <th><%= link_to post.url, post.url %></th>
      <th class="post_evaluation" data-score="<%= post.evaluation %>"></th>
      <th>
        <% if current_user.admin %>
          <%= link_to posts_change_auth_path(id: post.id) do %>
            <% if post.authorization %>
              <i class="fas fa-star"></i>
            <% else %>
              <i class="far fa-star"></i>
            <% end %>
          <% end %>
        <% else %>
          <% if post.authorization %>
            <i class="fas fa-star"></i>
          <% else %>
            <i class="far fa-star"></i>
          <% end %>
        <% end %>
      </th>
      <th><i class="far fa-comment-dots"></i><%= link_to "#{post.comments.count}件 ", post_path(post.id) %></th>
      <th id="like_buttons_<%= post.id %>" nowrap><%= render "likes/likes", post: post %></th>
　    <th><%= link_to '詳細', post_path(post), class: "btn btn-sm btn-info post_#{post.id}" %></th>
  </tr>
</div>
<% end %>




  <script>
  $('.post_evaluation').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
　</script>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <% @post.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-auto offset-sm-1">
      <h4>投稿編集</h4>
    </div>
    <%= render 'form', post: @post %>
  </div>

app/views/posts/index.html.erb
<div class="row justify-content-end">
<% if user_signed_in? %>
   <%= render 'searchs/search' %>
<% end %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
<table class='table'>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>URL</th>
      <th>評価</th>
      <th>公認</th>
      <th>コメント</th>
      <th>いいね</th>
      <th>投稿詳細</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'index', posts: @posts  %>
  </tbody>
</table>
  </div>
</div>


  <script>
    $('.post-evaluation').raty({
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      },
      path: '/assets/'
    });
  </script>
  <%= render 'layouts/fixed_btn' %>
  <div class="row justify-content-center">
  <%= paginate @posts %>
  </div>

app/views/posts/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-2'>
      <h2>新規投稿</h2>
    </div>
  </div>
    <%= render 'form', post: @post %>
  </div>

app/views/posts/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>

  		<h2>投稿</h2>
  		      <div class="d-flex justify-content-end"> <div id="like_buttons_<%= @post.id %>" nowrap><%= render "likes/likes", post: @post %></div></div>
  		      <div class="d-flex justify-content-end"> <% if current_user.id == @user.id %>
            <div><%= link_to '編集', edit_post_path(@post), class: "btn btn-sm btn-success edit_book_#{@post.id}" %></div>
            <div><%= link_to '削除', post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_#{@post.id}"%></div>
            <% end %></div>
            <div class="d-flex justify-content-end"><%= link_to '戻る', posts_path, class: "btn btn-sm btn-info" %></div>
  		    <div class="d-flex justify-content-end">by<%= @post.user.name %></div>
  		    <div class="d-flex justify-content-center">[<%= @post.sauna_name %>]
  		       <% if current_user.admin %>
                <%= link_to posts_change_auth_path(id: @post.id) do %>
                  <% if @post.authorization %>
                    <i class="fas fa-star"></i>
                  <% else %>
                    <i class="far fa-star"></i>
                  <% end %>
                <% end %>
              <% else %>
                <% if @post.authorization %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
              <% end %></div>
  		      <div class="d-flex justify-content-center"><%= attachment_image_tag(@post, :sauna_image, :fill, 700, 500, fallback: "no_image.jpg") %></div></br>
            <div class="d-flex justify-content-center">住所<i class="fas fa-location-arrow"></i>[<%= @post.address %>]</div>
            <div class="d-flex justify-content-center">HP<i class="fas fa-link"></i>[<%=link_to @post.url, @post.url %>]</div>
            <div class="d-flex justify-content-center">サウナ温度<i class="fas fa-hot-tub"></i>[<%= @post.sauna_temperature %>]</div>
            <div class="d-flex justify-content-center">水風呂温度<i class="fas fa-temperature-low"></i>[<%= @post.water_bath_temperature %>]</div>
            <div class="d-flex justify-content-center">外気浴<i class="fas fa-chair"></i>[<%= @post.outside_air_bath %>]</div>
            <div class="d-flex justify-content-center">混雑具合<i class="fas fa-user-alt-slash"></i>[<%= @post.congestion %>]</div>
            <div class="d-flex justify-content-center">時間帯<i class="fas fa-clock"></i>[<%= @post.time_zorn %>]</div>
            <div class="d-flex justify-content-center">瓶ジュース<i class="fas fa-wine-glass-alt"></i>[<%= @post.vending_machine %>]</div>
            <div class="d-flex justify-content-center">総合評価<i class="fas fa-check-circle"></i>[
            <div class="post_evaluation" data-score="<%= @post.evaluation %>"></div>]</div>

            <div class="row">
              <div class="offset-md-8 col-md-4">
            <% if @comment.errors.any? %>
              <%= @comment.errors.count %>件のエラーが発生しました
              <% @comment.errors.full_messages.each do |message| %>
                <%= message %>
              <% end %>
              <% end %>
              </div>
            </div>

            <div class="row">
              <div class="offset-md-8 col-md-4">
              <%= form_with(model:[@post, @comment], local: true) do |f| %>
              <%= f.text_area :comment, rows:'3',placeholder: "コメントをここに" %>
              <%= f.submit "送信する" %>
              <% end %>
              </div>
              <div class="col-md-6">
                <div id= "map">
              </div>
              </div>
              <div class=" col-md-6"><i class="far fa-comment-dots"></i>︎<%= @post.comments.count %>
              <table class="table">
                <% @post.comments.each do |comment| %>
                 <tr>
                  <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
                  <td><%= comment.comment %></td>
                  <td>by<%= comment.user.name %></td>
                  <td><% if comment.user == current_user %>
                      <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete %>
                      <% end %>
                  </td>
                 </tr>
                <% end %>
              </table>
                 </div>
            </div>




        <script>
        $('.post_evaluation').raty({
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          readOnly: true,
          score: function() {
            return $(this).attr('data-score');
          }
        });
      　</script>

      　<style>
          #map {
            height: 400px;
            width: 100%;
          }
        </style>
        <script>
        var map;
        function initMap() {
          map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: gon.post.latitude, lng: gon.post.longitude},
            zoom: 10
          });
        }
      　</script>

        <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API']%>&callback=initMap"></script>