config/routes.rb
Rails.application.routes.draw do
  #user用
  devise_for :users,skip: [:passwords,], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
 

  root to: 'user/homes#top'
  get 'homes/about' => 'user/homes#about'
  get 'user/mypage' => 'user#mypage'
  get '/search', to: 'searchs#search'


  # 会員側のルーティング設定

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :followings, :followers
    end

  resources :relationships, only: [:create, :destroy]
  end

  get '/posts/change_auth', to: 'posts#change_auth'
  

  resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    get 'authorization', as: 'authorization'
  end

  resources :contacts, only: [:new, :create]
    post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
    post 'contacts/back', to: 'contacts#back', as: 'back'
    get 'done', to: 'contacts#done', as: 'done'


  end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    # viewのform_tagにて
    # 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入した、
    # search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    # 選択したモデルがuserだったら
    if model == 'user'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
        User.where(name: content)
      # 選択した検索方法がが部分一致だったら
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    # 選択したモデルがpostだったら
    elsif model == 'post'
      if method == 'perfect'
        Post.where(sauna_name: content)
      else
        Post.where('sauna_name LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searchs/_search.html.erb
<% if user_signed_in? %>
  <div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "ユーザ" => "user", "投稿" => "post" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
</div>
<% end %>

app/views/searchs/search.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>

<% if @model == 'user' %>
    <h3>ユーザ検索結果 "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% elsif @model == 'post' %>
    <h3>投稿検索結果 "<%= @content %>"</h3>
  <%= render 'posts/index', posts: @records %>
<% end %>

　　</div>
　</div>
</div>